apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: taomish
  title: Taomish Backstage
  description: An example of a Backstage application.
  annotations:
    github.com/project-slug: tulasids/fusionpact-devops-challenge
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: user:default/tulasids5
  lifecycle: experimental
