version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: fusionpact-frontend
    ports:
      - "8080:80"

  backend:
    build: ./backend
    container_name: fusionpact-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data
