version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: fusionpact-frontend
    ports:
      - "8080:80"


  backend:
    build: ./backend
    container_name: fusionpact-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always
